global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gnc-web'
    static_configs:
      - targets: ['web:5173']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'gnc-production'
    static_configs:
      - targets: ['production:80']
    scrape_interval: 30s
    metrics_path: '/health'

  - job_name: 'postgres'
    static_configs:
      - targets: ['database:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['cache:6379']
    scrape_interval: 30s
